[package]
name = "rpg"
version = "0.1.0"
authors = ["Daniel Wehner <daniel@tag1consulting.com>"]

[dependencies]
docopt = "~0.6.11"
rustc-serialize = "0.3"
rand = "0.7"
num = "0.2.1"
num-bigint = "0.2.6"
num-traits = "0.2.11"
